sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "RwvNx/iL7ri5ifgane6n8jxCXWFuywtNwwwAfvRE4v9sD7o7bnw/RX7BRYLG+YWi1e2udykW2M0LFBMJAxpfc0OMoS6DrusUlcAdOmKPXIqMq6kYvEuKaGjP75GUACaBxY7G35rhZyKMiiybytxju4laX2K+Jl1MKDM5EEJx6LNKhgwupAHYh5Aj9Fkgm3XQaO8gpP0uliItbfMnvA+3GOYcsi0HT5qoP75SJdvsVPAAGp9L8JUGgQUxk/095EkhA08qaWfU8B/bLDigR8h5VyffexxPZQzCVQ982aS+SkDo+SF65okUDVZSJ6OHuFdqzzf9byNZUP4WlubzagmF22ZM7FIxcO5tLdLD+k86gPsM+CDtQUvkydmqVbYbsUR+SmknszP5w7qfrsb3ZcqDVz7FIJS0ptCcESbIOaHXTG+VzRKt/JtBEOQ+cKejeU8SIMWAlXf/t3SBLJGNvwBDAgkmtJVaNBZd+V/cnfOfdo9cFHia76xwFOkGv2E+nmNPGob7FZf5MIo0KwQ99YtYEkUENIw94qGDmyl0XcooWrlT2BBIkxDujGicMZNp7LD+Ztj03WnFqZihdgSSopcK6LURBPTlrzcAa4J79DLxQxpQ4xBKa+gS19CvxXIw8egSmCeVC0rEqO3ixbbNbjm2/VWfOoifJFO5L8MvIvH6yNY="
  only:
    - master
